name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Create Configuration Files
        env:
          CONFIG_FIREBASE: ${{secrets.CONFIG_FIREBASE}}
          CONFIG_SPOTIFY: ${{secrets.CONFIG_SPOTIFY}}
        run: |
          echo "${CONFIG_FIREBASE}" > ./src/Config/firebase.js
          echo "${CONFIG_SPOTIFY}" > ./src/Config/spotify.js

      - name: Build Source
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BRAGI_3000 }}"
          channelId: live
          projectId: bragi-3000
